[package]
name = "grep_core"
version = "0.1.0"
authors = ["TAMURA Dai <kirinode0@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.5"
